config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :boards

  resources :posts, only: [:create, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
  end


  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
  validates :text, presence: true

  def self.search(search)
    if search
      Post.where(['text LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :title, presence: true

  def self.search(search)
    if search
      Topic.where(['title LIKE ?', "%#{search}%"])
    else
      Topic.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @topics=Topic.search(params[:search]).order(id: "DESC")
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to({action: :show, id: @topic.id}, notice: 'スレッドが作成されました')}
        format.json { render :show, status: :created, location: @topic}
      else
        format.html {render :new}
        format.json {render json: @topic.errors, status: :unprocessable_entity}
      end
    end
  end

  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def show
    @posts = Post.where(topic_id: params[:id]).search(params[:search])
    @newpost = Post.new(:topic_id => params[:id])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to({action: :show, id: @topic.id}, notice: 'スレッドを更新しました')}
        format.json { render :show, status: :ok, location: @topic}
      else
        format.html {render :edit}
        format.json {render json: @topic.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'スレッドが削除されました'}
      format.json { head :no_content}
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment].permit(:post_id, :text))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to({controller: :posts, action: :show, id: @comment.post_id}, notice: '返信を行いました')}
        format.json { render action :show, status: :created, location: @comment}
      else
        format.html {render action :show , id: @comment.id }
        format.json {render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  before_action :set_comment, only: [:destroy]

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to({controller: :posts, action: :show, id: @comment.post_id}, notice: '投稿が削除されました')}
      format.json { head :no_content}
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = Post.new(params[:post].permit(:topic_id, :text))

    respond_to do |format|
      if @post.save
        format.html { redirect_to({controller: :boards, action: :show, id: @post.topic_id}, notice: '投稿が作成されました')}
        format.json { render action :show, status: :created, location: @post}
      else
        format.html {render action :show , id: @post.id }
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  before_action :set_post, only: [:show, :destroy]

  def show
    @comments = Comment.where(post_id: params[:id])
    @newcomment = Comment.new(:post_id => params[:id])
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to({controller: :boards, action: :show, id: @post.topic_id}, notice: '投稿が削除されました')}
      format.json { head :no_content}
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :topic_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/edit.html.erb
<div id ='main'>
  <h1>スレッドを編集</h1>

  <%= form_for(@topic, :url => board_path(@topic))  do |f| %>


    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <%= link_to 'スレッドの詳細を見る', board_path(@topic.id) %>
  <%= link_to 'スレッド一覧へ戻る', boards_path %>
</div>

app/views/boards/index.html.erb
<div id ='main'>
  <p id="notice"><%= notice %></p>

  <h1>掲示板</h1>

  <p>検索</p>
  <%= form_tag boards_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>スレッド</th>
      </tr>
    </thead>

    <tbody>
      <% @topics.each do|topic| %>
      <tr>
        <td><%= link_to topic.title, board_path(topic) %></td>
        <td><%= link_to '編集', edit_board_path(topic) %></td>
        <td><%= link_to '削除', board_path(topic), method: :delete, data: {confirm: "本当に削除しますか?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '新規スレッド作成', new_board_path %>
</div>

app/views/boards/new.html.erb
<div id ='main'>
  <%= form_for(@topic, :url => boards_path)  do |f| %>


    <div class="field">
      <%= f.label "スレッド名" %>
      <%= f.text_field :title, :size=>"60"%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  <%= link_to '戻る', boards_path %>
</div>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  スレッド名:<%= @topic.title %>
</h1>

<p>検索</p>
<%= form_tag board_path(@topic), :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <tbody>
  <% @posts.each_with_index do |post , idx| %>
    <tr>
      <td><%= idx + 1 %>.</td>
      <td>
        <strong><%= post.text %></strong>
      </td>
      <td><%= link_to "コメントを送る", post_path(post) %></td>
      <td><%= link_to '削除', post_path(post), method: :delete, data: {confirm: "本当に削除しますか?"} %></td>
    </tr>
    <% post.comments.each do |comment| %>
      <tr>
        <td>＞</td>
        <td><%= comment.text %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>


<h3>新規投稿</h3>
<%= form_for @newpost, :url => posts_path do |f| %>
  <p>本文</p>
  <p><%= f.text_area :text,:size=>"40" %></p>
  <%= f.hidden_field :topic_id %>
  <%= f.submit %>
<% end %>

<%= link_to 'スレッド一覧へ戻る' , boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AteamTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, :url => posts_path)  do |f| %>


  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  投稿:<%= @post.text %>
</h2>

<table>
  <tbody>
  <% @comments.each_with_index do |comment , idx| %>
    <tr>
      <td>＞</td>
      <td><%= comment.text %></td>
      <td><%= link_to '削除', post_comment_path(:post_id => @post.id, :id => comment.id), method: :delete, data: {confirm: "本当に削除しますか?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<h3>コメント投稿</h3>
<%= form_for @newcomment, :url => post_comments_path(@post) do |f| %>
  <p><%= f.text_area :text,:size=>"40"%></p>
  <%= f.hidden_field :post_id %>
  <%= f.submit %>
<% end %>

<p>
  <%= link_to '元のスレッドへ戻る' , board_path(@post.topic_id) %>
</p>
<p>
  <%= link_to 'スレッド一覧へ戻る' , boards_path %>
</p>